<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ModbusRTU_EM_Bell" Id="{82da657d-d222-4279-baf3-7e4e6d4c96bd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ModbusRTU_EM_Bell
VAR_INPUT
	MB_FirstUnitID: BYTE;
	MB_LastUnitID:  BYTE;
	EM_First: INT := 1;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>