<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OneUPS" Id="{fe5a4b71-962f-4cd6-a458-c9252ca306bb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK OneUPS
VAR_INPUT
	Crit_Alm:BOOL;
	Minor_Alm:BOOL;
	ByPass_Mode:BOOL;
	Batt_Mode: BOOL;
	Offline: BOOL;	
END_VAR
VAR_OUTPUT
END_VAR
VAR_TEMP
	i:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>